---
quizzes:
  - name: A
  - name: B
  - name: C
  - name: D
    roster:
      - position: 1
        quiz: A
      - position: 1
        quiz: B
      - position: 1
        quiz: C
  - name: E
    roster:
      - position: 2
        quiz: A
      - position: 2
        quiz: B
      - position: 2
        quiz: C
  - name: F
    roster:
      - position: 3
        quiz: A
      - position: 3
        quiz: B
      - position: 3
        quiz: C
  - name: G
    roster:
      - position: 2
        quiz: D
      - position: 3
        quiz: D
      - position: 1
        quiz: E
  - name: H
    roster:
      - position: 2
        quiz: E
      - position: 3
        quiz: E
      - position: 1
        quiz: F
  - name: I
    roster:
      - position: 2
        quiz: G
      - position: 3
        quiz: G
      - position: 1
        quiz: H
  - name: J
    roster:
      - position: 1
        quiz: D
      - position: 1
        quiz: G
      - position: 1
        quiz: I
rankings:
  - position: 1
    quiz: J
  - position: 2
    quiz: J
  - position: 3
    quiz: J
  - position: 2
    quiz: I
  - position: 3
    quiz: I
  - position: 2
    quiz: H
  - position: 3
    quiz: H
  - position: 2
    quiz: F
  - position: 3
    quiz: F
